Feat/task1
majishanred/webbee-task1 pull request #3
Opened 2024-06-18 18:10 UTC by majishanred

Полностью завершенная таска 1.

2024-06-18 19:07 UTC, myaak requested changes
Нужно поменять роутинг.

2024-06-18 19:07 UTC, myaak commented on index.css
> +  text-decoration: none !important;
!important используем поминимуму. Он же перекрывает все.

Вешать стили на селектор плохо. Можно потом на грабли встать классные

2024-06-18 19:07 UTC, myaak commented on index.css
> +  z-index: -99;
З индексы лучше точно выносить в переменные типа --modal-index и тд

2024-06-18 19:07 UTC, myaak commented on index.css
> +  --bg-1: #f1f1f1;
Переменные некоторые названы оч странно. Че за bg-1. Обычно есть Primary, secondary или хотя

2024-06-18 19:07 UTC, myaak commented on index.css
> +  border-radius: 9999px;
Выглядит как чето непонятное, можно сделать в %

2024-06-18 19:07 UTC, myaak commented on index.html
> +    <script src="./timer.js"></script>
Что за скрипты внизу Предательские????
Подумай как избежать этого

2024-06-18 19:07 UTC, myaak commented on index.js
> +window.addEventListener('click', (e) => {
Никаких онкликов. Говорил же на синке.
!!!!! КРИТИЧЕСКААЯ
+ он тут висит на window, что? Раз у тебя есть события, то можешь использовать их для роутинга кстати =)

2024-06-18 19:07 UTC, myaak commented on timer.js
> +      this.count += 1;
Инкременты копят ошибочку во время интервалов. По хорошему сделать по-другому.

2024-06-18 19:07 UTC, myaak commented on map.js
> +window.addEventListener('finishedLoading', (e) => {
А резве нельзя это сделать не в каждом контроллере, а например в роутере

2024-06-18 19:07 UTC, myaak commented on timer.js
> +class Timer {
Почему решил сделать классом. Можно описать обычным скриптом с функциями и переменными

2024-06-18 19:07 UTC, myaak commented on views/map.html
> +<script src="/map.js"></script>
Оу ноу, что он тут делает

2024-06-21 16:58 UTC, myaak requested changes
Вижу непоправленные моменты после ревью + не вижу галочек что ты сделал

2024-06-21 16:58 UTC, myaak commented on index.js
> +        view.scripts.forEach((script) => script());
Сомнительно, конечно. Можно бвло бы сделать кастомный ивент и вызывать его. А в хендлере сделать подписку и вызов скриптов. Но так тоже можно.

2024-06-21 16:58 UTC, myaak commented on index.js
> +  let view = routes[location.pathname];
У тебя ниже идет проверка на `if (view)`. Можно сделать чето типа 404 page и пихнуть сюда `routes[location.pathname] || routes['404'];` И не писать этот else

2024-06-21 16:58 UTC, myaak commented on index.html
>      <script src="./index.js"></script>
Не пофиксил

2024-06-21 16:58 UTC, myaak commented on index.js
> +  let pauseDate;
Зачем стопить таймер. По факту скажу правду даже не обязательно чтобы таймер тикал если ты не на странице таймера)
Тогда  и `savedDiff` не нужен будет

2024-06-21 16:58 UTC, myaak commented on index.js
> +    container ? container.appendChild(timerElement) : false;
такие вещи лучше в `if` конечно

2024-06-21 16:58 UTC, myaak commented on index.js
> +    let href = link.href.split('http://localhost:8080')[1];
А если я буду не на localhost???

2024-06-21 19:27 UTC, majishanred commented on index.html
>      <script src="./index.js"></script>
А что именно? Другие скрипты я убрал, остался только главный.

2024-06-21 19:58 UTC, myaak commented on index.html
>      <script src="./index.js"></script>
Суть не в том, что должен остаться один скрипт. По хорошему все скрипты в head подключаются. Ты столкнулся с проблемой что у тебя querySelector работает раньше, чем DOM загрузился. Почитай про async defer

2024-06-21 20:12 UTC, myaak commented
Галочки нужно ставить после коммита. То есть ты исправил - залил - поставил галочки

2024-06-21 20:14 UTC, majishanred commented on index.html
>      <script src="./index.js"></script>
Понял, спасибо

2024-06-23 20:36 UTC, myaak commented
@IvanKoigerov

2024-06-24 13:05 UTC, IvanKoigerov commented on index.css
index.css обычно не называют, просто база

2024-06-24 13:05 UTC, IvanKoigerov commented on index.css
> +  --padding-s: 8px;
Лучше назвать spacing, тк ты это можешь юзать для margin и это уже диссонанс

2024-06-24 13:05 UTC, IvanKoigerov commented on index.css
> +  --background-secondary: #fafafa;
не называй цвета по его цвету используй primary secondary и тд, или называй по сущности к которой используешь
Дизайн может резко измениться глобально, и чтобы в одном месте ты мог спокойно поменять тут значение и везде он поменялся, а так голубой на фиолетовый ты сменить не можешь

2024-06-24 13:05 UTC, IvanKoigerov commented on index.css
Классное использование стилей, мне нравиться

2024-06-24 13:05 UTC, IvanKoigerov commented on index.css
> +}
к id лучше всего не вешать стили, он должен быть один на странице, а вот стили наоборот должны повторяться и быть реюзабельными

2024-06-24 13:05 UTC, IvanKoigerov commented on index.js
круто если бы в разных файлах писал логику, но и так нормис

2024-06-24 13:05 UTC, IvanKoigerov commented on index.js
> +  let startDate = new Date();
нет смысла в лет держать

2024-06-24 13:05 UTC, IvanKoigerov commented on index.js
> +  let timerElement = document.createElement('div');
не вижу смысла создавать элемент и встраивать его потом, это дорого, лучше уже в существующий менять значение, это уже будет дешевле

2024-06-24 13:05 UTC, IvanKoigerov commented on index.js
> +  });
Прикольно, но по заданию это не нужно было делать

2024-06-24 13:23 UTC, majishanred commented on index.js
> +  let timerElement = document.createElement('div');
Согласен.

2024-06-24 13:23 UTC, majishanred commented on index.js
> +  let startDate = new Date();
Да, похоже случайно лет вместо конст поставил.

2024-06-24 13:24 UTC, majishanred commented on index.css
> +  --background-secondary: #fafafa;
Понял.

2024-06-24 13:25 UTC, majishanred commented on index.css
> +  --padding-s: 8px;
А если допустим в период жизни проекта могут измениться маргины и паддинги, но измениться отедльно, допустим маргины все увеличаться там пикселя на 2, а паддинги наоборот уменьшатся?

2024-06-24 13:26 UTC, majishanred commented on index.css
> +}
Понял.

2024-06-24 13:30 UTC, majishanred commented on index.css
А как обычно главный называется, bundle.css main.css?

2024-06-24 13:32 UTC, IvanKoigerov commented on index.css
> +  --padding-s: 8px;
это все считается сеткой проекта, то есть если у тебя меняются глобально отступы, то они полноценно меняются вместе, дизайнеры же не придумывают как именно мы будем расстояния менять, а меняют у себя в макете везде и по своему, редко будет так меняться
Ну и зачастую используются не классы, а из темы theme.spacing в mui

2024-06-24 19:39 UTC, myaak approved these changes

2024-06-25 14:46 UTC, merged